from discord.ext import commands
import re

class FourSouls(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    links = [
	    [["cursed keeper head"], "http://pop-life.com/foursouls/data/cards/045CursedKeeperHead.png"],
        [["cursed horf"], "http://pop-life.com/foursouls/data/cards/046CursedHorf.png"],
        [["cursed fatty"], "http://pop-life.com/foursouls/data/cards/047CursedFatty.png"],
        [["cursed moms hand"], "http://pop-life.com/foursouls/data/cards/048CursedMomsHand.png"],
        [["cursed psy horf"], "http://pop-life.com/foursouls/data/cards/049CursedPsyHorf.png"],
        [["cursed gaper"], "http://pop-life.com/foursouls/data/cards/050CursedGaper.png"],
  	    [["cursed eye"], "https://croc.pw/foursouls/005CursedEye.png"],
  	    [["cursed globin"], "http://pop-life.com/foursouls/data/cards/010CursedGlobin.png"],
  	    [["cursed tumor"], "https://croc.pw/foursouls/009CursedTumor.png"],
        [["holy dip"], "http://pop-life.com/foursouls/data/cards/040HolyDip.png"],
        [["holy moms eye"], "http://pop-life.com/foursouls/data/cards/041HolyMomsEye.png"],
        [["holy dinga"], "http://pop-life.com/foursouls/data/cards/042HolyDinga.png"],
        [["holy keeper head"], "http://pop-life.com/foursouls/data/cards/043HolyKeeperHead.png"],
        [["holy squirt"], "http://pop-life.com/foursouls/data/cards/044HolySquirt.png"],
        [["holy bony"], "http://pop-life.com/foursouls/data/cards/007HolyBony.png"],
        [["holy chest"], "https://croc.pw/foursouls/014HolyChest.png"],
        [["holy mulligan"], "http://pop-life.com/foursouls/data/cards/008HolyMulligan.png"],
        [["hourglass", "hour glass"], "http://pop-life.com/foursouls/data/cards/016Hourglass.png"],
        [["relic"], "http://pop-life.com/foursouls/data/cards/001TheRelic.png"],
        [["dads lost coin"], "http://pop-life.com/foursouls/data/cards/002DadsLostCoin(1).png"],
        [["finger"], "http://pop-life.com/foursouls/data/cards/003Finger.png"],
        [["charged baby"], "http://pop-life.com/foursouls/data/cards/004ChargedBaby.png"],
        [["tarot cloth"], "http://pop-life.com/foursouls/data/cards/006TarotCloth.png"],
        [["moms box"], "http://pop-life.com/foursouls/data/cards/007MomsBox(1).png"],
        [["spider mod"], "http://pop-life.com/foursouls/data/cards/008SpiderMod(1).png"],
        [["eye of greed"], "http://pop-life.com/foursouls/data/cards/009EyeOfGReed(1).png"],
        [["moms razor"], "http://pop-life.com/foursouls/data/cards/010MomsRazor.png"],
        [["cheese grater"], "http://pop-life.com/foursouls/data/cards/011CheeseGrater.png"],
        [["dead bird"], "http://pop-life.com/foursouls/data/cards/012DeadBird.png"],
        [["dinner"], "http://pop-life.com/foursouls/data/cards/013Dinner.png"],
        [["breakfast"], "http://pop-life.com/foursouls/data/cards/014Breakfast.png"],
        [["synthoil"], "http://pop-life.com/foursouls/data/cards/015Synthoil.png"],
        [["meat"], "http://pop-life.com/foursouls/data/cards/016Meat!.png"],
        [["polydactyl"], "http://pop-life.com/foursouls/data/cards/017Polydactyl(1).png"],
        [["belly button"], "http://pop-life.com/foursouls/data/cards/018BellyButton(1).png"],
        [["brimstone"], "http://pop-life.com/foursouls/data/cards/019Brimstone.png"],
        [["ipecac"], "http://pop-life.com/foursouls/data/cards/020Ipecac.png"],
        [["moms purse"], "http://pop-life.com/foursouls/data/cards/021MomsPurse.png"],
        [["moms coin purse"], "http://pop-life.com/foursouls/data/cards/022momscoinpurse.png"],
        [["theres options"], "https://croc.pw/foursouls/23TheresOptions(1).png"],
        [["champion belt", "champions belt"], "https://croc.pw/foursouls/024ChampionBelt(1).png"],
        [["monstros tooth"], "http://pop-life.com/foursouls/data/cards/025monstrostooth(1).png"],
        [["dry baby"], "http://pop-life.com/foursouls/data/cards/026DryBaby.png"],
        [["goat head"], "http://pop-life.com/foursouls/data/cards/027GoatHead(2).png"],
        [["blue map"], "http://pop-life.com/foursouls/data/cards/028BlueMap.png"],
        [["compass"], "http://pop-life.com/foursouls/data/cards/029Compass.png"],
        [["map"], "http://pop-life.com/foursouls/data/cards/030Map.png"],
        [["fanny pack"], "http://pop-life.com/foursouls/data/cards/031FannyPack(1).png"],
        [["habit"], "http://pop-life.com/foursouls/data/cards/032TheHabit.png"],
        [["cambion conception"], "http://pop-life.com/foursouls/data/cards/033CambionConception(1).png"],
        [["greeds gullet"], "https://croc.pw/foursouls/034GreedsGullet(1).png"],
        [["suicide king"], "https://croc.pw/foursouls/035SuicideKing(1).png"],
        [["trinity shield"], "http://pop-life.com/foursouls/data/cards/036TrinityShield(2).png"],
        [["steamy sale"], "http://pop-life.com/foursouls/data/cards/037SteamySale.png"],
        [["shiny rock"], "http://pop-life.com/foursouls/data/cards/039ShinyRock.png"],
        [["midas touch"], "http://pop-life.com/foursouls/data/cards/040MidasTouch.png"],
        [["edens blessing"], "http://pop-life.com/foursouls/data/cards/041EdensBLessing(1).png"],
        [["polaroid"], "http://pop-life.com/foursouls/data/cards/042ThePolaroid.png"],
        [["starter deck"], "http://pop-life.com/foursouls/data/cards/043StarterDeck(1).png"],
        [["the chest"], "http://pop-life.com/foursouls/data/cards/044TheChest(1).png"],
        [["refresh"], "http://pop-life.com/foursouls/data/cards/045Refresh(1).png"],
        [["dark bum"], "http://pop-life.com/foursouls/data/cards/046DarkBum(1).png"],
        [["empty vessel"], "http://pop-life.com/foursouls/data/cards/047EmptyVessel(1).png"],
        [["bumbo treasure", "bumbo item"], "http://pop-life.com/foursouls/data/cards/048Bumbo(2).png"],
        [["sacred heart"], "http://pop-life.com/foursouls/data/cards/049SacredHeart.png"],
        [["curse of the tower"], "http://pop-life.com/foursouls/data/cards/050CurseOfTheTower(1).png"],
        [["baby haunt"], "http://pop-life.com/foursouls/data/cards/051BabyHaunt.png"],
        [["daddy haunt"], "http://pop-life.com/foursouls/data/cards/052DaddyHaunt.png"],
        [["bobs brain"], "http://pop-life.com/foursouls/data/cards/053BobsBrain.png"],
        [["two of clubs"], "http://pop-life.com/foursouls/data/cards/054TwoofClubs.png"],
        [["mr boom"], "http://pop-life.com/foursouls/data/cards/055MrBoom.png"],
        [["tech x"], "http://pop-life.com/foursouls/data/cards/056TechX(1).png"],
        [["razor blade"], "http://pop-life.com/foursouls/data/cards/057RazorBlade.png"],
        [["mini mush"], "http://pop-life.com/foursouls/data/cards/058MiniMush.png"],
        [["lucky foot"], "http://pop-life.com/foursouls/data/cards/059LuckyFoot.png"],
        [["spoon bender"], "http://pop-life.com/foursouls/data/cards/060SpoonBender.png"],
        [["flush"], "http://pop-life.com/foursouls/data/cards/061Flush!(1).png"],
        [["monster manual"], "http://pop-life.com/foursouls/data/cards/062MonsterManual.png"],
        [["shovel"], "https://croc.pw/foursouls/063TheShovel.png"],
        [["d20"], "http://pop-life.com/foursouls/data/cards/064D20.png"],
        [["potato peeler"], "http://pop-life.com/foursouls/data/cards/065PotatoPeeler.png"],
        [["sack head"], "http://pop-life.com/foursouls/data/cards/066SackHead.png"],
        [["bum friend"], "http://pop-life.com/foursouls/data/cards/067BumFriend.png"],
        [["compost"], "http://pop-life.com/foursouls/data/cards/068Compost(2).png"],
        [["diplopia"], "http://pop-life.com/foursouls/data/cards/069Diplopia(1).png"],
        [["battery"], "http://pop-life.com/foursouls/data/cards/070TheBattery(1).png"],
        [["blank card"], "http://pop-life.com/foursouls/data/cards/071BlankCard.png"],
        [["placebo"], "http://pop-life.com/foursouls/data/cards/072Placebo(1).png"],
        [["moms bra"], "http://pop-life.com/foursouls/data/cards/073MomsBra(1).png"],
        [["no"], "http://pop-life.com/foursouls/data/cards/074No!.png"],
        [["host hat"], "http://pop-life.com/foursouls/data/cards/075HostHat(1).png"],
        [["poop"], "http://pop-life.com/foursouls/data/cards/076ThePoop(2).png"],
        [["decoy"], "http://pop-life.com/foursouls/data/cards/077Decoy(2).png"],
        [["sack of pennies"], "http://pop-life.com/foursouls/data/cards/078SackofPennies(1).png"],
        [["jaw bone"], "http://pop-life.com/foursouls/data/cards/079JawBone.png"],
        [["boomerang"], "http://pop-life.com/foursouls/data/cards/080Boomerang(1).png"],
        [["contract from below"], "http://pop-life.com/foursouls/data/cards/081ContractfromBelow(1).png"],
        [["godhead"], "http://pop-life.com/foursouls/data/cards/082Godhead(1).png"],
        [["modeling clay"], "http://pop-life.com/foursouls/data/cards/083ModelingClay(2).png"],
        [["d100", "d one hundred"], "http://pop-life.com/foursouls/data/cards/084D100.png"],
        [["chaos"], "http://pop-life.com/foursouls/data/cards/085Chaos.png"],
        [["remote detonator"], "http://pop-life.com/foursouls/data/cards/086RemoteDetonator.png"],
        [["crystal ball"], "http://pop-life.com/foursouls/data/cards/087CrystalBall.png"],
        [["mystery sack"], "http://pop-life.com/foursouls/data/cards/088MysterySack(1).png"],
        [["donation machine"], "http://pop-life.com/foursouls/data/cards/089DonationMachine.png"],
        [["book of sin"], "http://pop-life.com/foursouls/data/cards/090BookofSin(1).png"],
        [["glass cannon"], "http://pop-life.com/foursouls/data/cards/091GlassCannon(1).png"],
        [["moms shovel"], "http://pop-life.com/foursouls/data/cards/092MomsShovel(1).png"],
        [["chaos card"], "http://pop-life.com/foursouls/data/cards/093ChaosCard.png"],
        [["box"], "http://pop-life.com/foursouls/data/cards/094Box!.png"],
        [["pandoras box"], "http://pop-life.com/foursouls/data/cards/095PandorasBox(2).png"],
        [["d4"], "http://pop-life.com/foursouls/data/cards/096D4(1).png"],
        [["battery bum"], "http://pop-life.com/foursouls/data/cards/097BatteryBum.png"],
        [["pay to play"], "http://pop-life.com/foursouls/data/cards/098PaytoPlay.png"],
        [["golden razor"], "http://pop-life.com/foursouls/data/cards/099GoldenRazor.png"],
        [["portable slot"], "http://pop-life.com/foursouls/data/cards/100PortableSlot.png"],
        [["smelter"], "http://pop-life.com/foursouls/data/cards/101Smelter.png"],
        [["dead cat"], "http://pop-life.com/foursouls/data/cards/102TheDeadCat.png"],
        [["guppys head"], "http://pop-life.com/foursouls/data/cards/103GuppysHead(2).png"],
        [["guppys paw"], "http://pop-life.com/foursouls/data/cards/104GuppysPaw.png"],
        [["guppys collar"], "http://pop-life.com/foursouls/data/cards/105GuppysCollar.png"],
        [["nickel"], "http://pop-life.com/foursouls/data/cards/043Nickel1(1).png"],
        [["blank rune"], "http://pop-life.com/foursouls/data/cards/070BlankRune(2).png"],
        [["blood penny"], "http://pop-life.com/foursouls/data/cards/073BloodPenny(1).png"],
        [["bomb"], "http://pop-life.com/foursouls/data/cards/055Bomb!1(1).png"],
        [["broken ankh"], "http://pop-life.com/foursouls/data/cards/077BrokenAnkh(2).png"],
        [["cains eye"], "http://pop-life.com/foursouls/data/cards/076CainsEye(2).png"],
        [["counterfeit penny"], "http://pop-life.com/foursouls/data/cards/075CounterfietPenny(2).png"],
        [["curved horn"], "http://pop-life.com/foursouls/data/cards/078CurvedHorn(1).png"],
        [["dagaz"], "http://pop-life.com/foursouls/data/cards/071Dagaz(1).png"],
        [["dice shard"], "http://pop-life.com/foursouls/data/cards/065DiceShard1(2).png"],
        [["dime"], "http://pop-life.com/foursouls/data/cards/048Dime(1).png"],
        [["ehwaz"], "http://pop-life.com/foursouls/data/cards/072Ehwaz(2).png"],
        [["four cents", "4 cents"], "http://pop-life.com/foursouls/data/cards/034FourCents1%20copy.png"],
        [["gold bomb", "golden bomb"], "http://pop-life.com/foursouls/data/cards/059GoldBomb(1).png"],
        [["golden horseshoe", "golden horse shoe"],
         "http://pop-life.com/foursouls/data/cards/080GoldenHorseshoe(2).png"],
        [["guppys hairball"], "http://pop-life.com/foursouls/data/cards/081GuppysHairball(1).png"],
        [["emperor"], "http://pop-life.com/foursouls/data/cards/087IVTheEmperor(1).png"],
        [["hermit"], "http://pop-life.com/foursouls/data/cards/092IXTheHermit(1).png"],
        [["lil battery"], "http://pop-life.com/foursouls/data/cards/060LilBattery1(1).png"],
        [["lost soul"], "http://pop-life.com/foursouls/data/cards/082LostSoul(1).png"],
        [["mega battery"], "http://pop-life.com/foursouls/data/cards/064MegaBattery(1).png"],
        [["one cent", "1 cent", "a penny"], "http://pop-life.com/foursouls/data/cards/001OneCent1%20copy.png"],
        [["blue pill"], "http://pop-life.com/foursouls/data/cards/053PillBlue(1).png"],
        [["red pill"], "http://pop-life.com/foursouls/data/cards/052PillRed(2).png"],
        [["yellow pill"], "http://pop-life.com/foursouls/data/cards/054PillYellow(1).png"],
        [["purple heart"], "http://pop-life.com/foursouls/data/cards/079PurpleHeart(2).png"],
        [["soul heart"], "http://pop-life.com/foursouls/data/cards/068SoulHeart1(1).png"],
        [["swallowed penny"], "http://pop-life.com/foursouls/data/cards/074SwallowedPenny(1).png"],
        [["empress"], "http://pop-life.com/foursouls/data/cards/086IIITheEmpress(1).png"],
        [["fool"], "http://pop-life.com/foursouls/data/cards/083TheFool(1).png"],
        [["high priestess"], "http://pop-life.com/foursouls/data/cards/085IITheHighPriestess(1).png"],
        [["magician"], "http://pop-life.com/foursouls/data/cards/084ITheMagician(1).png"],
        [["three cents", "3 cents"], "http://pop-life.com/foursouls/data/cards/019ThreeCents1%20copy.png"],
        [["two cents", "2 cents"], "http://pop-life.com/foursouls/data/cards/007TwoCents1%20copy.png"],
        [["heirophant"], "http://pop-life.com/foursouls/data/cards/088VTheHeirophant(2).png"],
        [["lovers"], "http://pop-life.com/foursouls/data/cards/089VITheLovers(1).png"],
        [["chariot"], "http://pop-life.com/foursouls/data/cards/090VIITheChariot(1).png"],
        [["justice"], "http://pop-life.com/foursouls/data/cards/091VIIIJustice(2).png"],
        [["wheel of fortune"], "http://pop-life.com/foursouls/data/cards/093XWheelofFortune(2).png"],
        [["strength"], "http://pop-life.com/foursouls/data/cards/094XIStrength(2).png"],
        [["the hanged man"], "http://pop-life.com/foursouls/data/cards/095XIITheHangedMan(2).png"],
        [["death"], "http://pop-life.com/foursouls/data/cards/096XIIIDeath(1).png"],
        [["tower"], "http://pop-life.com/foursouls/data/cards/097XIVTheTower(2).png"],
        [["sun"], "http://pop-life.com/foursouls/data/cards/102XIXTheSun(2).png"],
        [["temperance"], "http://pop-life.com/foursouls/data/cards/099XVITemperance(1).png"],
        [["stars"], "http://pop-life.com/foursouls/data/cards/100XVIITheStars(1).png"],
        [["moon"], "http://pop-life.com/foursouls/data/cards/101XVIIITheMoon(1).png"],
        [["judgement", "judgment"], "http://pop-life.com/foursouls/data/cards/103XXJudgement(2).png"],
        [["world"], "http://pop-life.com/foursouls/data/cards/104XXITheWorld(2).png"],
        [["clotty"], "http://pop-life.com/foursouls/data/cards/010Clotty(1).png"],
        [["cod worm"], "https://croc.pw/foursouls/014CodWorm(1).png"],
        [["daddy long legs"], "http://pop-life.com/foursouls/data/cards/079DaddyLongLegs(2).png"],
        [["delirium"], "http://pop-life.com/foursouls/data/cards/107Delirium(2).png"],
        [["gurdy"], "http://pop-life.com/foursouls/data/cards/073Gurdy(1).png"],
        [["hanger"], "http://pop-life.com/foursouls/data/cards/019Hanger(1).png"],
        [["moms eye"], "http://pop-life.com/foursouls/data/cards/035MomsEye(2).png"],
        [["peep"], "http://pop-life.com/foursouls/data/cards/099Peep(2).png"],
        [["pestilence"], "http://pop-life.com/foursouls/data/cards/084Pestilence(1).png"],
        [["portal"], "http://pop-life.com/foursouls/data/cards/029Portal(1).png"],
        [["duke of flies"], "http://pop-life.com/foursouls/data/cards/078DukeofFLies(1).png"],
        [["lamb"], "http://pop-life.com/foursouls/data/cards/106TheLamb(2).png"],
        [["war"], "http://pop-life.com/foursouls/data/cards/082War(2).png"],
        [["dip"], "http://pop-life.com/foursouls/data/cards/001Dip.png"],
        [["pooter"], "http://pop-life.com/foursouls/data/cards/002Pooter.png"],
        [["fly"], "http://pop-life.com/foursouls/data/cards/003Fly.png"],
        [["trite"], "http://pop-life.com/foursouls/data/cards/004Trite(1).png"],
        [["fatty"], "http://pop-life.com/foursouls/data/cards/005Fatty.png"],
        [["spider"], "http://pop-life.com/foursouls/data/cards/006Spider.png"],
        [["conjoined fatty"], "http://pop-life.com/foursouls/data/cards/007ConjoinedFatty.png"],
        [["pale fatty"], "http://pop-life.com/foursouls/data/cards/008PaleFatty(1).png"],
        [["leech"], "http://pop-life.com/foursouls/data/cards/009Leech(1).png"],
        [["red host"], "http://pop-life.com/foursouls/data/cards/011RedHost.png"],
        [["squirt"], "http://pop-life.com/foursouls/data/cards/012Squirt(1).png"],
        [["fat bat"], "http://pop-life.com/foursouls/data/cards/013FatBat.png"],
        [["swarm fly"], "http://pop-life.com/foursouls/data/cards/015SwarmFly.png"],
        [["black bony"], "http://pop-life.com/foursouls/data/cards/016BlackBony.png"],
        [["dinga"], "http://pop-life.com/foursouls/data/cards/017Dinga.png"],
        [["ring of flies"], "http://pop-life.com/foursouls/data/cards/018RingofFlies(1).png"],
        [["wizoob"], "http://pop-life.com/foursouls/data/cards/020Wizoob.png"],
        [["mulligan"], "http://pop-life.com/foursouls/data/cards/021mulligan.png"],
        [["hopper"], "http://pop-life.com/foursouls/data/cards/022Hopper(1).png"],
        [["keeper head"], "http://pop-life.com/foursouls/data/cards/023KeeperHead(1).png"],
        [["big spider"], "http://pop-life.com/foursouls/data/cards/024BigSpider.png"],
        [["boom fly"], "http://pop-life.com/foursouls/data/cards/025BoomFly.png"],
        [["leaper"], "http://pop-life.com/foursouls/data/cards/026Leaper.png"],
        [["dople"], "http://pop-life.com/foursouls/data/cards/027Dople(1).png"],
        [["psy horf"], "http://pop-life.com/foursouls/data/cards/028PsyHorf.png"],
        [["moms dead hand"], "http://pop-life.com/foursouls/data/cards/030MomsDeadHand.png"],
        [["greedling"], "http://pop-life.com/foursouls/data/cards/031Greedling.png"],
        [["dank globin"], "http://pop-life.com/foursouls/data/cards/032DankGlobin.png"],
        [["evil twin"], "http://pop-life.com/foursouls/data/cards/033EvilTwin(1).png"],
        [["mulliboom"], "http://pop-life.com/foursouls/data/cards/034Mulliboom.png"],
        [["rage creep"], "http://pop-life.com/foursouls/data/cards/036RageCreep(1).png"],
        [["horf"], "http://pop-life.com/foursouls/data/cards/037Horf(1).png"],
        [["moms hand"], "http://pop-life.com/foursouls/data/cards/038MomsHand.png"],
        [["stoney"], "http://pop-life.com/foursouls/data/cards/039Stoney(1).png"],
        [["gold chest", "golden chest"],
         "http://pop-life.com/foursouls/data/cards/051GoldChest1.png http://pop-life.com/foursouls/data/cards/052GoldChest2.png"],
        [["dark chest"],
         "http://pop-life.com/foursouls/data/cards/053DarkChest1(1).png http://pop-life.com/foursouls/data/cards/054DarkChest2(1).png"],
        [["chest"],
         "http://pop-life.com/foursouls/data/cards/055Chest1.png http://pop-life.com/foursouls/data/cards/056Chest2.png"],
        [["secret room"], "http://pop-life.com/foursouls/data/cards/057SecretRoom.png"],
        [["xl floor"], "http://pop-life.com/foursouls/data/cards/058XLFLoor.png"],
        [["shop upgrade"], "http://pop-life.com/foursouls/data/cards/059ShopUpgrade.png"],
        [["we need to go deeper"], "https://croc.pw/foursouls/060WeNeedtogoDeeper.png"],
        [["i can see forever"], "http://pop-life.com/foursouls/data/cards/061IcanSeeForever.png"],
        [["troll bombs"], "http://pop-life.com/foursouls/data/cards/062TrollBombs.png"],
        [["mega troll bomb"], "http://pop-life.com/foursouls/data/cards/063MegaTrollBomb.png"],
        [["ambush"], "http://pop-life.com/foursouls/data/cards/064Ambush.png"],
        [["greed (happening)"], "http://pop-life.com/foursouls/data/cards/065Greed!.png"],
        [["deal with the devil", "devil deal"], "http://pop-life.com/foursouls/data/cards/066DealWithTheDevil.png"],
        [["devil"], "http://pop-life.com/foursouls/data/cards/098XVTheDevil(2).png"],
        [["cursed chest"], "http://pop-life.com/foursouls/data/cards/067CursedChest.png"],
        [["curse of amnesia"], "http://pop-life.com/foursouls/data/cards/068CurseofAmnesia.png"],
        [["curse of greed"], "http://pop-life.com/foursouls/data/cards/069CurseofGreed.png"],
        [["curse of loss"], "https://croc.pw/foursouls/070CurseofLoss.png"],
        [["curse of pain"], "http://pop-life.com/foursouls/data/cards/071CurseofPain.png"],
        [["curse of the blind"], "http://pop-life.com/foursouls/data/cards/072CurseoftheBlind(1).png"],
        [["monstro"], "http://pop-life.com/foursouls/data/cards/074Monstro.png"],
        [["little horn"], "http://pop-life.com/foursouls/data/cards/075LittleHorn(2).png"],
        [["dark one"], "http://pop-life.com/foursouls/data/cards/076DarkOne(2).png"],
        [["larry jr"], "http://pop-life.com/foursouls/data/cards/077LarryJr.png"],
        [["mega fatty"], "http://pop-life.com/foursouls/data/cards/080MegaFatty(1).png"],
        [["famine"], "http://pop-life.com/foursouls/data/cards/081Famine.png"],
        [["death"], "http://pop-life.com/foursouls/data/cards/083Death.png"],
        [["conquest"], "http://pop-life.com/foursouls/data/cards/085Conquest.png"],
        [["pride"], "http://pop-life.com/foursouls/data/cards/086Pride.png"],
        [["wrath"], "http://pop-life.com/foursouls/data/cards/087Wrath.png"],
        [["gluttony"], "http://pop-life.com/foursouls/data/cards/088Gluttony(1).png"],
        [["envy"], "http://pop-life.com/foursouls/data/cards/089Envy.png"],
        [["greed (boss)"], "http://pop-life.com/foursouls/data/cards/090Greed.png"],
        [["lust"], "http://pop-life.com/foursouls/data/cards/091Lust.png"],
        [["sloth"], "http://pop-life.com/foursouls/data/cards/092Sloth.png"],
        [["green bloat", "bloat green"], "http://cloud-3.steamusercontent.com/ugc/793126531755051221/782F2221EDB3C791D6AA8B9291FCAAB5401C45F5/"],
        [["cute bloat", "bloat cute"], "http://cloud-3.steamusercontent.com/ugc/1023950208133551078/602573DAE39C413450515E001F766C3206A798C3/"],
        [["bloat"], "http://pop-life.com/foursouls/data/cards/094TheBloat.png"],
        [["chub"], "http://pop-life.com/foursouls/data/cards/095Chub.png"],
        [["scolex"], "http://pop-life.com/foursouls/data/cards/096Scolex.png"],
        [["gemini"], "http://pop-life.com/foursouls/data/cards/097Gemini.png"],
        [["gurdy jr"], "http://pop-life.com/foursouls/data/cards/098GurdyJr.png"],
        [["ragman"], "http://pop-life.com/foursouls/data/cards/100Ragman(1).png"],
        [["carrion queen"], "http://pop-life.com/foursouls/data/cards/101CarrionQueen.png"],
        [["haunt"], "http://pop-life.com/foursouls/data/cards/102TheHaunt(1).png"],
        [["mask of infamy"], "http://pop-life.com/foursouls/data/cards/103MaskOfInfamy(1).png"],
        [["satan"], "http://pop-life.com/foursouls/data/cards/105Satan!.png"],
        [["blue baby"], "http://pop-life.com/foursouls/data/cards/008BlueBaby(1).png"],
        [["cain"], "http://pop-life.com/foursouls/data/cards/002Cain(1).png"],
        [["eden"], "http://pop-life.com/foursouls/data/cards/011Eden(1).png"],
        [["eve"], "http://pop-life.com/foursouls/data/cards/006Eve(1).png"],
        [["isaac character"], "http://pop-life.com/foursouls/data/cards/001Isaac(1).png"],
        [["judas"], "http://pop-life.com/foursouls/data/cards/004Judas(1).png"],
        [["lazarus"], "http://pop-life.com/foursouls/data/cards/009Lazarus(2).png"],
        [["lilith"], "http://pop-life.com/foursouls/data/cards/007Lilith(1).png"],
        [["maggy"], "http://pop-life.com/foursouls/data/cards/003Maggy(2).png"],
        [["samson"], "http://pop-life.com/foursouls/data/cards/005Samson(1).png"],
        [["forgotten"], "http://pop-life.com/foursouls/data/cards/010TheForgotten(3).png"],
        [["blood lust"], "http://pop-life.com/foursouls/data/cards/005BloodLust(4).png"],
        [["book of belial"], "http://pop-life.com/foursouls/data/cards/004BookofBelial(3).png"],
        [["forever alone"], "http://pop-life.com/foursouls/data/cards/008ForeverAlone(3).png"],
        [["incubus"], "http://pop-life.com/foursouls/data/cards/007Incubus(4).png"],
        [["lazarus rags"], "http://pop-life.com/foursouls/data/cards/009LazarusRags(4).png"],
        [["sleight of hand"], "http://pop-life.com/foursouls/data/cards/002SleightofHand(3).png"],
        [["bone"], "http://pop-life.com/foursouls/data/cards/010TheBone(3).png"],
        [["d6"], "http://pop-life.com/foursouls/data/cards/001D6(4).png"],
        [["yum heart"], "http://pop-life.com/foursouls/data/cards/003YumHeart(4).png"],
        [["soul of gluttony"], "http://pop-life.com/foursouls/data/cards/002SoulofGluttony.png"],
        [["soul of greed"], "http://pop-life.com/foursouls/data/cards/001SoulofGreed.png"],
        [["soul of guppy"], "http://pop-life.com/foursouls/data/cards/003SoulofGuppy.png"],
        [["hush"], "http://pop-life.com/foursouls/data/cards/017Hush(4).png"],
        [["sack"], "http://pop-life.com/foursouls/data/cards/015Sack(2).png"],
        [["apollyon"], "http://pop-life.com/foursouls/data/cards/004Apollyon(1).png"],
        [["azazel"], "http://pop-life.com/foursouls/data/cards/003Azazel(1).png"],
        [["begotten"], "http://pop-life.com/foursouls/data/cards/010Begotten(4).png"],
        [["boil"], "http://pop-life.com/foursouls/data/cards/002Boil(3).png"],
        [["cancer"], "http://pop-life.com/foursouls/data/cards/020Cancer(2).png"],
        [["charged penny"], "http://pop-life.com/foursouls/data/cards/009ChargedPenny(2).png"],
        [["charger"], "http://pop-life.com/foursouls/data/cards/009Charger(2).png"],
        [["credit card"], "http://pop-life.com/foursouls/data/cards/016CreditCard(3).png"],
        [["crooked penny"], "http://pop-life.com/foursouls/data/cards/017CrookedPenny(1).png"],
        [["curse of fatigue"], "http://pop-life.com/foursouls/data/cards/014CurseofFatigue(2).png"],
        [["curse of tiny hands"], "http://pop-life.com/foursouls/data/cards/013CurseofTinyHands(2).png"],
        [["dads key"], "http://pop-life.com/foursouls/data/cards/006DadsKey(2).png"],
        [["deaths head"], "http://pop-life.com/foursouls/data/cards/005DeathsHead(6).png"],
        [["fistula"], "http://pop-life.com/foursouls/data/cards/020Fistula(3).png"],
        [["fruit cake"], "http://pop-life.com/foursouls/data/cards/013FruitCake(2).png"],
        [["gaper"], "http://pop-life.com/foursouls/data/cards/004Gaper(4).png"],
        [["guppys tail"], "http://pop-life.com/foursouls/data/cards/011GuppysTail(2).png"],
        [["gurglings"], "http://pop-life.com/foursouls/data/cards/018Gurglings(5).png"],
        [["prayer card"], "http://pop-life.com/foursouls/data/cards/012PrayrCard(4).png"],
        [["i am error"], "http://pop-life.com/foursouls/data/cards/012IAmError(2).png"],
        [["not butter bean", "wait what"], "http://pop-life.com/foursouls/data/cards/014ICantBelieve(2).png"],
        [["butter bean loot"], "http://pop-life.com/foursouls/data/cards/049ButterBean1(1).png"],
        [["butter bean treasure", "butter bean item"], "http://pop-life.com/foursouls/data/cards/018ButterBean(1).png"],
        [["butter bean"], "Please specify: butter bean (loot), butter bean (treasure)"],
        [["imp"], "http://pop-life.com/foursouls/data/cards/007Imp(4).png"],
        [["infamy"], "http://pop-life.com/foursouls/data/cards/008Infamy(2).png"],
        [["jera"], "http://pop-life.com/foursouls/data/cards/017Jera(2).png"],
        [["joker"], "http://pop-life.com/foursouls/data/cards/011Joker(2).png"],
        [["knight"], "http://pop-life.com/foursouls/data/cards/008Knight(3).png"],
        [["lemon mishap"], "http://pop-life.com/foursouls/data/cards/019LemonMishap(3).png"],
        [["library card"], "http://pop-life.com/foursouls/data/cards/015LibraryCard(1).png"],
        [["libra"], "https://croc.pw/foursouls/018Libra.png"],
        [["lord of the pit"], "http://pop-life.com/foursouls/data/cards/003LordofthePit(3).png"],
        [["moms knife"], "http://pop-life.com/foursouls/data/cards/005MomsKnife(3).png"],
        [["more options"], "https://croc.pw/foursouls/002MoreOptions(4).png"],
        [["nine volt", "9 volt"], "http://pop-life.com/foursouls/data/cards/009NineVolt(2).png"],
        [["ouija board"], "http://pop-life.com/foursouls/data/cards/012OuijaBoard(3).png"],
        [["parabite"], "https://croc.pw/foursouls/003Parabite(2).png"],
        [["pill purple"], "http://pop-life.com/foursouls/data/cards/018PillPurple(2).png"],
        [["pink eye"], "http://pop-life.com/foursouls/data/cards/019PinkEye(2).png"],
        [["placenta"], "http://pop-life.com/foursouls/data/cards/004Placenta(2).png"],
        [["plan c"], "http://pop-life.com/foursouls/data/cards/020PlanC(3).png"],
        [["polycephalus"], "http://pop-life.com/foursouls/data/cards/015Polycephalus(4).png"],
        [["ragling"], "http://pop-life.com/foursouls/data/cards/001Ragling(3).png"],
        [["round worm"], "http://pop-life.com/foursouls/data/cards/006RoundWorm(3).png"],
        [["skeleton key"], "http://pop-life.com/foursouls/data/cards/003SkeletonKey(2).png"],
        [["soy milk"], "http://pop-life.com/foursouls/data/cards/010SoyMilk(3).png"],
        [["steven"], "http://pop-life.com/foursouls/data/cards/019Steven(5).png"],
        [["succubus"], "http://pop-life.com/foursouls/data/cards/007Succubus(2).png"],
        [["bible"], "http://pop-life.com/foursouls/data/cards/016TheBible(2).png"],
        [["cage"], "http://pop-life.com/foursouls/data/cards/016TheCage(3).png"],
        [["holy mantle"], "http://pop-life.com/foursouls/data/cards/001HolyMantle(4).png"],
        [["keeper"], "http://pop-life.com/foursouls/data/cards/002TheKeeper(2).png"],
        [["lost"], "http://pop-life.com/foursouls/data/cards/001TheLost(2).png"],
        [["missing page"], "http://pop-life.com/foursouls/data/cards/001TheMissingPage(4).png"],
        [["trap door"], "http://pop-life.com/foursouls/data/cards/011TrapDoor(2).png"],
        [["two of diamonds"], "http://pop-life.com/foursouls/data/cards/013TwoofDiamonds(2).png"],
        [["void"], "http://pop-life.com/foursouls/data/cards/004Void(4).png"],
        [["wooden nickel"], "http://pop-life.com/foursouls/data/cards/002WoodenNickel(3).png"],
        [["one up", "1up"], "http://pop-life.com/foursouls/data/cards/013OneUp.png"],
        [["twenty twenty", "2020"], "http://pop-life.com/foursouls/data/cards/020TwentyTwenty.png"],
        [["aaa battery"], "http://pop-life.com/foursouls/data/cards/022AAABattery.png"],
        [["abaddon"], "https://croc.pw/foursouls/013Abaddon.png"],
        [["angel room"], "http://pop-life.com/foursouls/data/cards/018AngelRoom.png"],
        [["ansuz"], "http://pop-life.com/foursouls/data/cards/019Ansuz.png"],
        [["athame"], "http://pop-life.com/foursouls/data/cards/027Athame.png"],
        [["bag o trash"], "http://pop-life.com/foursouls/data/cards/006BagoTrash.png"],
        [["black candle"], "http://pop-life.com/foursouls/data/cards/024BlackCandle.png"],
        [["black rune"], "http://pop-life.com/foursouls/data/cards/020BlackRune.png"],
        [["blastocyst"], "http://pop-life.com/foursouls/data/cards/024Blastocyst.png"],
        [["bony"], "http://pop-life.com/foursouls/data/cards/005Bony.png"],
        [["boss rush"], "https://croc.pw/foursouls/019BossRush.png"],
        [["brain"], "http://pop-life.com/foursouls/data/cards/012Brain.png"],
        [["bumbo character"], "http://pop-life.com/foursouls/data/cards/002Bumbo.png"],
        [["curse of blood lust", "curse of bloodlust"],
         "http://pop-life.com/foursouls/data/cards/021CurseofBloodLust.png"],
        [["curse of impulse"], "https://croc.pw/foursouls/020CurseofImpulse.png"],
        [["daddy long legs"], "http://pop-life.com/foursouls/data/cards/011DaddyLongLegs.png"],
        [["dark arts"], "http://pop-life.com/foursouls/data/cards/008DarkArts.png"],
        [["dark judas"], "http://pop-life.com/foursouls/data/cards/004DarkJudas.png"],
        [["dice shard"], "http://pop-life.com/foursouls/data/cards/015DiceShard.png"],
        [["dingle"], "https://croc.pw/foursouls/023Dingle.png"],
        [["distant admiration"], "http://pop-life.com/foursouls/data/cards/023DistantAdmiration.png"],
        [["euthanasia"], "http://pop-life.com/foursouls/data/cards/003Euthanasia.png"],
        [["flaming hopper"], "https://croc.pw/foursouls/003FlamingHopper.png"],
        [["forget me now"], "https://croc.pw/foursouls/028ForgetMeNow.png"],
        [["game breaking bug"], "http://pop-life.com/foursouls/data/cards/017GameBreakingBug_.png"],
        [["get out of jail"], "http://pop-life.com/foursouls/data/cards/029GetOutofJail.png"],
        [["gimpy"], "http://pop-life.com/foursouls/data/cards/007Gimpy.png"],
        [["globin"], "https://croc.pw/foursouls/004Globin.png"],
        [["gold key", "golden key"], "https://croc.pw/foursouls/030GoldKey.png"],
        [["guppys eye"], "http://pop-life.com/foursouls/data/cards/014GuppysEye.png"],
        [["head of krampus"], "http://pop-life.com/foursouls/data/cards/030HeadofKrampus.png"],
        [["head of the keeper"], "http://pop-life.com/foursouls/data/cards/004HeadoftheKeeper.png"],
        [["head trauma"], "http://pop-life.com/foursouls/data/cards/017HeadTrauma.png"],
        [["headless horseman"], "https://croc.pw/foursouls/029Headlesshorseman.png"],
        [["infestation"], "http://pop-life.com/foursouls/data/cards/005Infestation.png"],
        [["isaac boss"], "https://croc.pw/foursouls/028Isaac_.png"],
        [["krampus"], "http://pop-life.com/foursouls/data/cards/027Krampus.png"],
        [["lard"], "http://pop-life.com/foursouls/data/cards/007Lard.png"],
        [["lil battery"], "http://pop-life.com/foursouls/data/cards/016LilBattery.png"],
        [["magnet"], "http://pop-life.com/foursouls/data/cards/022Magnet.png"],
        [["mama haunt"], "http://pop-life.com/foursouls/data/cards/015MamaHaunt.png"],
        [["moms eye shadow", "moms eyeshadow"], "http://pop-life.com/foursouls/data/cards/006MomsEyeShadow.png"],
        [["moms heart"], "https://croc.pw/foursouls/030MomsHeart.png"],
        [["monstro ii", "monstro 2"], "https://croc.pw/foursouls/025MonstroII.png"],
        [["mutant spider"], "https://croc.pw/foursouls/026MutantSpider.png"],
        [["nerve ending"], "http://pop-life.com/foursouls/data/cards/013NerveEnding.png"],
        [["phd"], "http://pop-life.com/foursouls/data/cards/009PHD.png"],
        [["perthro"], "http://pop-life.com/foursouls/data/cards/018Perthro.png"],
        [["black pill"], "http://pop-life.com/foursouls/data/cards/025PillBlack.png"],
        [["spotty pill", "spot pill", "spotted pill"], "http://pop-life.com/foursouls/data/cards/026PillSpots.png"],
        [["white pill"], "http://pop-life.com/foursouls/data/cards/027PillWhite.png"],
        [["poker chip"], "http://pop-life.com/foursouls/data/cards/023PokerChip.png"],
        [["polyphemus"], "http://pop-life.com/foursouls/data/cards/001Polyphemus.png"],
        [["? card", "question card", "question mark card"],
        "https://croc.pw/foursouls/028QuestionCard.png"],
        [["rainbow baby"], "http://pop-life.com/foursouls/data/cards/021RainbowBaby.png"],
        [["red candle"], "http://pop-life.com/foursouls/data/cards/025RedCandle.png"],
        [["roundy"], "http://pop-life.com/foursouls/data/cards/002Roundy.png"],
        [["rubber cement"], "http://pop-life.com/foursouls/data/cards/008RubberCement.png"],
        [["smart fly"], "http://pop-life.com/foursouls/data/cards/019SmartFly.png"],
        [["spiked chest"], "http://pop-life.com/foursouls/data/cards/015SpikedChest.png"],
        [["sucker"], "https://croc.pw/foursouls/001Sucker.png"],
        [["swarmer"], "http://pop-life.com/foursouls/data/cards/011Swarmer.png"],
        [["tape worm"], "http://pop-life.com/foursouls/data/cards/021TapeWorm.png"],
        [["telepathy for dummies"], "https://croc.pw/foursouls/010TelepathyforDummies.png"],
        [["fallen"], "http://pop-life.com/foursouls/data/cards/026TheFallen.png"],
        [["left hand"], "http://pop-life.com/foursouls/data/cards/024LeftHand.png"],
        [["wiz"], "https://croc.pw/foursouls/002TheWiz.png"],
        [["tumor"], "https://croc.pw/foursouls/006Tumor.png"],
        [["whore of babylon"], "http://pop-life.com/foursouls/data/cards/003WhoreofBabylon.png"],
        [["widow"], "http://pop-life.com/foursouls/data/cards/022Widow.png"],
        [["bumbo"], "Please specify: bum-bo (character), bum-bo (treasure)"],
        [["isaac"], "Please specify: isaac (character), isaac (boss)"],
        [["lil gish"], "http://cloud-3.steamusercontent.com/ugc/1023950208133509619/07C6B7E1E799263D9D42ECFBB9B188E8ECC78690/"],
        [["gish"], "https://i.imgur.com/Lv3lAsP.jpg"],
        [["dead eye"], "https://croc.pw/foursouls/dead_eye.png"],
        [["marked"], "https://croc.pw/foursouls/marked.png"],
        [["epic fetus"], "https://croc.pw/foursouls/epic_fetus.png"],
        [["tapeworm monster", "tapeworm enemy"], "https://i.imgur.com/kwzJ3AR.png"],
        [["tapeworm character"], "https://i.imgur.com/gvbR2RR.png"],
        [["rainbow tapeworm"], "https://i.imgur.com/NpmeT6l.png"],
        [["tapeworm"], "Please specify: tapeworm (character), tapeworm (monster)"],
        [["black proglottid"], "https://i.imgur.com/9XbFU3S.png"],
        [["red proglottid"], "https://i.imgur.com/ZUxqqJY.png"],
        [["pink proglottid"], "https://i.imgur.com/3tPoQvX.png"],
        [["white proglottid"], "https://i.imgur.com/EkX8vBL.png"],
        [["proglottid"], "Please specify: black proglottid, red proglottid, pink proglottid, white proglottid"],
        [["dickknot", "dick knot"], "**NSFW** ||https://i.imgur.com/oWpFf8j.png||"],
        [["curse"], "http://pop-life.com/foursouls/data/cards/006TheCurse(4).png"],
        [["mom"], "http://pop-life.com/foursouls/data/cards/104Mom!.png"],
        [["d10", "d ten"], "http://pop-life.com/foursouls/data/cards/005D10(1).png"],
        [["guppy"], "http://pop-life.com/foursouls/data/cards/001Guppy%20(2).png"],
        [["pin"], "http://pop-life.com/foursouls/data/cards/093Pin.png"],
        [["shadow"], "http://pop-life.com/foursouls/data/cards/038Shadow(1).png"],
        [["greed"], "Please specify: greed (character), greed (boss)"],
	[["corrupteddata", "corrupted data"], "https://i.ibb.co/82z02C0/Untitled.png"],
	[["ultrapride", "ultra pride"], "https://i.ibb.co/dQGzM2B/Untitled.png"],
	[["edengirl", "girleden", "eden girl", "girl eden"], "https://i.imgur.com/wwFwbOo.png"],
	[["edenboy", "boyeden", "eden boy", "boy eden"], "https://i.imgur.com/OOwGph7.png"]   
    ]

    @commands.Cog.listener()
    async def on_message(self, message):
        guilds = [123641386921754625, 485099143786922018, 273609483060641792]
        if not message.guild.id in guilds:
            return
        regex = re.compile('[^a-zA-Z0-9? ]')
        try:
            for string in re.findall('\[\[[^\]]*\]\]', message.content):
                string = regex.sub('', string.lower()[2:-2])
                for link in self.links:
                    for name in link[0]:
                        if string == name:
                            await message.channel.send(link[1])
                            raise Exception("Stop")
                for link in self.links:
                    for name in link[0]:
                        if name in string:
                            await message.channel.send(link[1])
                            raise Exception("Stop")
        except Exception:
            pass




def setup(bot):
    bot.add_cog(FourSouls(bot))
