# Replace YOUR_TOKEN_HERE with the token of your Discord bot.
token: YOUR_TOKEN_HERE

# Jerbot can load plugins from multiple different folders.
# By default, this is just the plugins folder, but more can be added as needed.
plugin_folders:
  - plugins
  - example_submodule