### One of these files needs to exist for every server Jerbot is deployed into.
### Rename this file to the ID of the server being configured.

# Any feature (or subfeature) not wanted in the server being configured can simply be omitted from the configuration file.

# This configures the blocklist functionality. You can put as many blocklisted words here as necessary for your setup.
blocklist:
  exempt_roles:
  - YOUR_ROLE_ID_HERE
  triggers:
  - "YOUR_BLOCKLISTED_WORD_HERE"
  - "YOUR_SECOND_BLOCKLISTED_WORD_HERE"
  # These are regex, in cases where a simple word won't do (or it isn't in the dictionary!).
  # Don't worry about whitespace or capitalization, that's automatically removed.
  regex_triggers:
  - "YOUR_SPECIAL_BLOCKLISTED_WORD_HERE"
  dm_color:     0xffffff
  log_color:    0xffffff
  channel:  YOUR_CHANNEL_ID_HERE