### One of these files needs to exist for every server Jerbot is deployed into.
### Rename this file to the ID of the server being configured.

# Any feature (or subfeature) not wanted in the server being configured can simply be omitted from the configuration file.

# This configures the automessage plugin, which sends an automatic message at the specified interval.
automessage:
  - crontab:  "* * * * *" # This example crontab runs the automessage task every minute. Generate your own at https://crontab.guru/
    channel:  YOUR_CHANNEL_ID_HERE
    message:  "YOUR_MESSAGE_CONTENT_HERE"

# This configures the channels and embed colors for moderation log functionality.
# As stated above, any subfeature not wanted here can simply be removed.
modlogs:
  message_edits:
      channel:  YOUR_CHANNEL_ID_HERE
      color:    0xffffff #Any hex color code is accepted.
  message_deletes:
      channel:  YOUR_CHANNEL_ID_HERE
      color:    0xffffff
  member_joins:
      channel:  YOUR_CHANNEL_ID_HERE
      color:    0xffffff
      new_account_color:    0xffffff # This color is used when an account is under seven days old.
  member_leaves:
      channel:  YOUR_CHANNEL_ID_HERE
      color:    0xffffff
  member_bans:
      channel:  YOUR_CHANNEL_ID_HERE
      color:    0xffffff

# This configures the blacklist functionality. You can put as many blacklisted words here as necessary for your setup.
blacklist:
  triggers:
  - "YOUR_BLACKLISTED_WORD_HERE"
  - "YOUR_SECOND_BLACKLISTED_WORD_HERE"
  dm_color:     0xffffff
  log_color:    0xffffff
  log_channel:  YOUR_CHANNEL_ID_HERE